core/src/main/scala/com/criteo/cuttle/App.scala
core/src/main/scala/com/criteo/cuttle/Executor.scala
examples/src/main/scala/com/criteo/cuttle/examples/HelloWorld.scala
timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeseriesApp.scala
timeseries/src/test/scala/com/criteo/cuttle/timeseries/TimeSeriesSpec.scala

- add streaming
- add info about stuck jobs

TimeSeries: improve focus route

---

core/src/main/javascript/app/components/Window.js

Change-Id: I33765e59e16744c50191e5bb038186b6e952876e

Fix style for execution window

---

.eslintrc
package.json
yarn.lock

Note that we have ~180 errors/warns we should care about one day :)

eslint tweaks

---

core/src/main/scala/com/criteo/cuttle/Cuttle.scala
core/src/main/scala/com/criteo/cuttle/Executor.scala
examples/src/main/scala/com/criteo/cuttle/examples/HelloWorld.scala
timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeseriesScheduler.scala

Useless and pollute the public API with one more concept.

Remove SubmittedExecution.

---

core/src/main/scala/com/criteo/cuttle/Cuttle.scala
core/src/main/scala/com/criteo/cuttle/local/LocalPlatform.scala
core/src/main/scala/com/criteo/cuttle/local/package.scala
core/src/main/scala/com/criteo/cuttle/package.scala
examples/src/main/scala/com/criteo/cuttle/examples/HelloWorld.scala

Move LocalPlatform into its own package.

---

build.sbt
core/src/main/javascript/app/pages/Execution.js
core/src/main/scala/com/criteo/cuttle/Executor.scala
core/src/main/scala/com/criteo/cuttle/package.scala
core/src/main/scala/com/criteo/cuttle/platforms/local/LocalPlatform.scala

Small UI & API fixes.

---

.eslintrc
core/src/main/javascript/ApplicationState.js
core/src/main/javascript/Utils.js
core/src/main/javascript/app/components/JobSelector.js
core/src/main/javascript/app/components/JobStatus.js
core/src/main/javascript/app/components/Link.js
core/src/main/javascript/app/components/PopoverMenu.js
core/src/main/javascript/app/components/Spinner.js
core/src/main/javascript/app/pages/Execution.js
core/src/main/javascript/app/pages/ExecutionLogs.js
core/src/main/javascript/graph/dagger/render/d3render.js

No more errors, could be useful to make eslint break builds, not sure of what is a good way to achieve this, through sbt call `yarn eslint` or maybe invoking from webpack

Eslint: fix and adjust rules

---

core/src/main/scala/com/criteo/cuttle/Executor.scala

This fix the JSON API being unresponsive when a large number of jobs are
started. Extracting the list of 'waiting' executions from the platforms can
be costly (and it was for Local because the list is wrapped in a STM). So
it must be batched.
(On my laptop it changes from 2mins to 50ms for 5000 started executions)

Fix API performance issue

---

core/src/main/javascript/app/components/Badge.js
core/src/main/javascript/app/pages/ExecutionLogs.js
core/src/main/scala/com/criteo/cuttle/Executor.scala
core/src/main/scala/com/criteo/cuttle/platforms/RateLimiter.scala
package.json
yarn.lock

- Use a single transaction to launch all executions.
- Optimize display for large number of executions.

Optimize for large number of jobs

---

timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesScheduler.scala

Fix a bug where the state wasn't serialized upon changes.

TimeSeries: fix state serialization

---

core/src/main/javascript/App.js
core/src/main/javascript/app/pages/CalendarFocus.js
core/src/main/javascript/app/pages/Execution.js
core/src/main/javascript/datamodel.js
core/src/main/javascript/index.js
core/src/main/scala/com/criteo/cuttle/Executor.scala
core/src/main/scala/com/criteo/cuttle/platforms/local/LocalPlatform.scala
core/src/main/style/index.less

- Display context in the execution detail screen
- Indicate more clearly when an execution is waiting
- Fix some scrollbar issues

Some UI fixes

---

core/src/main/javascript/App.js
core/src/main/javascript/ApplicationState.js
core/src/main/javascript/app/components/PopoverMenu.js
core/src/main/javascript/app/pages/BackfillCreate.js
core/src/main/javascript/app/pages/Backfills.js
core/src/main/javascript/app/pages/Calendar.js
core/src/main/javascript/app/pages/CalendarFocus.js
core/src/main/javascript/app/pages/ExecutionLogs.js
core/src/main/javascript/app/pages/TimeSeriesExecutions.js
core/src/main/javascript/index.js
package.json
timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesApp.scala
timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesScheduler.scala
yarn.lock

UI still ugly but that works a lot better and is more clean.
Added [redux-form](https://github.com/erikras/redux-form) as it helps a lot for form validation.

[backfills] list skeleton & create form

---

core/src/main/javascript/index.js

Now only gray the application if the connection has been lost for more than 15s, removing the
flickering when connections are closed because of inactivity.

Fix gray overlay flickering

---

timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesScheduler.scala

IntervalSet overrides `.contains` which messes with the equality
operator. Comparing to the empty IntervalSet is still safe so we compute
the diff then check whether it's empty.

TimeSeries: fix incomplete period detection in backfill creation

---

core/src/main/javascript/app/pages/CalendarFocus.js

Remove all transitions, get back to React lifecycle

Basic control for 12 hours in Calendar

---

examples/src/main/scala/com/criteo/cuttle/examples/HelloWorld.scala
timeseries/src/main/scala/com/criteo/cuttle/timeseries/Database.scala
timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesApp.scala
timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesScheduler.scala

Basic queryBackfills to read table will be reworked when working on UI with paging

[backfills] Add Table and create/update backfills persistence

---

core/src/main/javascript/ApplicationState.js
core/src/main/javascript/app/components/BackfillStatus.js
core/src/main/javascript/app/components/TimeRangeLink.js
core/src/main/javascript/app/pages/BackfillCreate.js
core/src/main/javascript/app/pages/Backfills.js
core/src/main/javascript/app/pages/ExecutionLogs.js
core/src/main/javascript/app/utils/Date.js
core/src/main/javascript/datamodel.js
core/src/main/javascript/index.js
timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesScheduler.scala

Basic implementation of backfills list.
No paging so far, would prefer to refactor pagination first + not sure that it is really required for backfills.
Also fixes backfill creation and refactors some code.

Backfills list

---

core/src/main/javascript/app/pages/Execution.js
core/src/main/javascript/app/pages/Workflow.js
core/src/main/javascript/graph/dagger/render/nodesAndEdges.js
core/src/main/style/index.less
package.json
yarn.lock

Change to a monospace font for graph node names
Fix padding in descriptions

Layout fixes in job details

---

core/src/main/scala/com/criteo/cuttle/Database.scala
core/src/main/scala/com/criteo/cuttle/Executor.scala

Basically with want to ensure that even when sorted on a column, the execution list
is then displayed in the execution order.

Make sorting more stable.

---

core/src/main/javascript/app/pages/ExecutionLogs.js

Execution logs fix

---

core/src/main/scala/com/criteo/cuttle/App.scala

Default route was not served anymore, so /executions/paused &
others were 404.

Fixes routes

---

core/src/main/javascript/app/pages/Execution.js
core/src/main/javascript/app/utils/URLHighlighter.js
examples/src/main/scala/com/criteo/cuttle/examples/HelloWorld.scala
package.json
yarn.lock

Uses https://github.com/gregjacobs/Autolinker.js/

Adds link highlighting in job logs

---

core/src/main/javascript/ApplicationState.js
core/src/main/javascript/app/components/BackfillStatus.js
core/src/main/javascript/app/components/Badge.js
core/src/main/javascript/app/menu/Menu.js
core/src/main/javascript/app/pages/Backfills.js
core/src/main/javascript/datamodel.js
core/src/main/javascript/index.js
core/src/main/scala/com/criteo/cuttle/App.scala
core/src/main/scala/com/criteo/cuttle/Scheduling.scala
timeseries/src/main/scala/com/criteo/cuttle/timeseries/Database.scala
timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesApp.scala
timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesScheduler.scala

- Menu Badge: Displays count of running backfills
- Resume uncompleted backfills on start
- Reload list when backfill started/completed
- List styling / sorts order tweaks

Backfills: Improvements

---

core/src/main/javascript/app/pages/ExecutionLogs.js

Displays a "failure" badge that opens the last failure log when clicked.

Adds a "last failure" column for stuck jobs

---

build.sbt
core/src/main/scala/com/criteo/cuttle/Workflow.scala

Can be usefull for programatically generated workflows.

Empty workflow builder.

---

core/src/main/javascript/index.js

It could not be displayed anymore once it had been cancelled.

Fixes connection error display

---

core/src/main/scala/com/criteo/cuttle/Utils.scala

Threads created by executors are usually pooled to run more than one task submitted to the executor - often this is a performance optimisation
to reuse threads so they run more than one task (as creating new thread is an expensive operation). Depending on the implementation and
configuration of the thread pool, it might keep the threads running forever or terminate when they are unused for some time.
Marking the thread as daemon won't block the program from exiting when there are still such threads running.

Make the thread pool used for delayed execution return daemon threads

---

core/src/main/scala/com/criteo/cuttle/platforms/ExecutionPool.scala
timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesScheduler.scala
timeseries/src/test/scala/com/criteo/cuttle/timeseries/TimeSeriesSpec.scala

- Moves backfills to a Ref[Set] rather than TSet
- Extracts pure state transitions functions
- Fixes a few warnings

Minor refactorings

---

core/src/main/scala/com/criteo/cuttle/App.scala
core/src/main/scala/com/criteo/cuttle/Executor.scala

- graceful with configurable and default grace period
- hard

Adds endpoint shutdown capabilities

---

core/src/main/scala/com/criteo/cuttle/Executor.scala
core/src/main/scala/com/criteo/cuttle/Workflow.scala
core/src/main/scala/com/criteo/cuttle/package.scala
core/src/main/scala/com/criteo/cuttle/platforms/local/LocalPlatform.scala
core/src/test/scala/com/criteo/cuttle/CuttleSpec.scala
examples/src/main/scala/com/criteo/cuttle/examples/HelloWorld.scala
timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesScheduler.scala
timeseries/src/test/scala/com/criteo/cuttle/timeseries/TimeSeriesSpec.scala

Future[Completed] instead of Future[Unit] to avoid mistakes in user code because of
value discarding.
From Scala language specification:
If e has some value type and the expected type is Unit, e is converted to the expected
type by embedding it in the term { e; () }.

Change the signature of the SideEffect function.

---

core/src/main/scala/com/criteo/cuttle/platforms/local/LocalPlatform.scala
core/src/main/scala/com/criteo/cuttle/platforms/local/package.scala
examples/src/main/scala/com/criteo/cuttle/examples/HelloWorld.scala

We don't allow to execute a complex shell scripts in sh interpolation in the sake of a guarantee that forked process will be killed when you want to cancel or pause it.

we don't do a double fork in a local platform any more

---

build.sbt

Release 0.2.2

---

build.sbt

- Remove companion object that was shadowing an apply function (#199)
- Fix stuck jobs number and paused jobs in calendar (#196)
- Makes sure Execution thunks are run in Try (#195)

Release 0.2.3

---

build.sbt

- allow multiple MySQL endpoints

Release 0.2.4

---

core/src/main/scala/com/criteo/cuttle/App.scala
core/src/main/scala/com/criteo/cuttle/Executor.scala
core/src/main/scala/com/criteo/cuttle/Metrics.scala
timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesScheduler.scala

Expose the following Prometheus metrics:
* Job status count by tags
* Average last success time by tags

Add Prometheus metrics by job tags

---

build.sbt

Release 0.2.5

---

core/src/main/scala/com/criteo/cuttle/App.scala
core/src/main/scala/com/criteo/cuttle/Executor.scala
core/src/main/scala/com/criteo/cuttle/Metrics.scala
core/src/main/scala/com/criteo/cuttle/Scheduling.scala
timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesScheduler.scala

* Expose Prometheus metrics for relative latency of time series jobs

Add relative latency metrics

---

core/src/main/javascript/app/components/Error.js
core/src/main/javascript/app/components/StreamView.js
core/src/main/javascript/app/components/TextWithDashedLine.js
core/src/main/javascript/app/pages/BackfillCreate.js
core/src/main/javascript/app/pages/Execution.js
examples/src/main/scala/com/criteo/cuttle/examples/HelloWorld.scala
timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesApp.scala
timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesScheduler.scala

- now we can backfill a hourly job for one period only with its daily dependencies being properly backfilled
- now we have one precise error by each check on backfill creation
- errors are displayed in a proper UI widget
- I extract some UI components that I thought I can reuse for backfill's UI but at the end I didn't use them. However I consider this change as a good practice for React as a way to have smaller components.

better error handling on backfill creation

---

package.json
webpack.config.js
yarn.lock

Single quotes were replaced by double quotes by automatic `prettier-eslint`.

adding webpack dev server

---

core/src/main/scala/com/criteo/cuttle/App.scala

- the user should explicitly use hard or gracePeriodSeconds as query parameters

Update shutdown endpoint

---

core/src/main/scala/com/criteo/cuttle/CuttleProject.scala

This change allow a more flexible way to start Cuttle. You can now get only needed routes and bootstrap the server externally (to add some routes or custom behaviour)

allow to start server externally (#225)

---

webpack.config.js

- fonts were not loaded due to incorrect paths

Fix font path resolving

---

core/src/main/scala/com/criteo/cuttle/graph/package.scala
timeseries/src/test/scala/com/criteo/cuttle/timeseries/TimeSeriesSpec.scala

Fix workflow validation

---

build.sbt

- UI: finished executions are now sorted starting from the most recent one
- API: schema migration fo database changes is now exposed through `utils.updateSchema`
- Bugfixes: fix state inconsistencies for timeseries intervals (https://github.com/criteo/cuttle/pull/252), workflow validation (https://github.com/criteo/cuttle/pull/256)

Release 0.3.5

---

build.sbt
core/src/it/scala/com/criteo/cuttle/DatabaseITest.scala
core/src/it/scala/com/criteo/cuttle/DatabaseSuite.scala
core/src/it/scala/com/criteo/cuttle/DoobieLogsHandler.scala
core/src/it/scala/com/criteo/cuttle/TestScheduling.scala
core/src/main/javascript/app/pages/Jobs.js
core/src/main/javascript/app/pages/Workflow.js
core/src/main/scala/com/criteo/cuttle/App.scala
core/src/main/scala/com/criteo/cuttle/Database.scala
core/src/main/scala/com/criteo/cuttle/ExecutionStreams.scala
core/src/main/scala/com/criteo/cuttle/Executor.scala

BTW, I introduced integration tests of database migrations with doobie scalatest.

introducing author and date of pause in paused state

---

core/src/main/javascript/ApplicationState.js
core/src/main/javascript/app/menu/Menu.js
core/src/main/javascript/app/pages/Jobs.js
core/src/main/javascript/app/pages/Workflow.js
core/src/main/javascript/index.js

- Remove the description column, as the content can be multi-line markdown texts
- Add a link to show the job detail

Job list improvements

---

core/src/main/javascript/graph/dagger/render/nodesAndEdges.js

- Fix the issue when some job names cannot be correctly displayed

Fix graph node display issue

---

core/src/main/scala/com/criteo/cuttle/Database.scala

In order to speed up Execution stream query

Add PK on execution_streams id

---

core/src/main/scala/com/criteo/cuttle/Workflow.scala

As these can be used in a csv manner for Filtering in UI for instance.
Also, scalafmt fun, do not blame me :)

Job id document valid characters

---

core/src/main/javascript/app/pages/ExecutionLogs.js
core/src/main/scala/com/criteo/cuttle/App.scala
core/src/main/scala/com/criteo/cuttle/Executor.scala

- status was "running" for every stuck execution
- added sorting as well

Fixes statuses on the stuck page

---

build.sbt

Release 0.3.10

---

core/src/main/scala/com/criteo/cuttle/CuttleProject.scala
core/src/main/scala/com/criteo/cuttle/Executor.scala

Starting a project with lots of executions can lead to issues, such as
full CPU or being killed not answering a health-check in time.
By pausing them at startup, it can allow to analyze / fix the state
before starting jobs.
Also, in `pauseJobs` method, do not pause jobs already paused to avoid losing user actions.

Start project with jobs paused

---

timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesScheduler.scala

The initial version of Cuttle did not cancel concurrent running executions.
If any, the scheduler would wait for them to finish before starting the backfills.
Miscellaneous:
Fixed an issue which would cause the backfills not to be registered in the state DB.

Fix a bug which caused backfill states not to be persisted in the state DB

---

README.md
build.sbt

- Performance issue with large number of execution (#303)
- Version support (#299)
- Remove cancellation of concurrent executions when running backfills (#301)
- [Timeseries UI] Fixed empty jobs view and non-updated states in calendar view (#300)

Version 0.4.1

---

timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesScheduler.scala

Introduced by https://github.com/criteo/cuttle/pull/299

Fixes bug that prevented backfills from being marked as finished

---

core/src/main/scala/com/criteo/cuttle/Executor.scala
core/src/main/scala/com/criteo/cuttle/Scheduling.scala
examples/src/main/scala/com/criteo/cuttle/examples/HelloCustomScheduling.scala

Couple of minor compilation warnings fixed

Warnings cleanup

---

timeseries/src/main/javascript/app/pages/CalendarFocus.js
timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesApp.scala

Hovering over a period where a job is paused now displays "job XXX is paused - <period start> <period end>" instead of "job XXX is todo"

Display todo paused jobs as paused jobs instead of todo jobs in the focused calendar view

---

.gitignore
build.sbt
core/src/main/scala/com/criteo/cuttle/Executor.scala
core/src/main/scala/com/criteo/cuttle/Utils.scala
cron/src/main/scala/com/criteo/cuttle/cron/CronModel.scala
cron/src/main/scala/com/criteo/cuttle/cron/CronScheduler.scala
examples/src/main/scala/com/criteo/cuttle/examples/HelloCronScheduling.scala

Loop for each registered job:
1 Compute next CRON event for this job (based on the CRON expression)
2 Wait for the CRON event to occur
3 Create a CronContext and run the job side-effect
4 Wait on the side-effect Future result
5 If Failure, go to 3 if we want to retry, otherwise go to 1
TODO:
- ui isn't implemented yet
- configure the number of retries per job
- persist scheduler state to DB

[WIP] MVP of Cron Scheduler

---

timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesScheduler.scala
timeseries/src/main/scala/com/criteo/cuttle/timeseries/package.scala
timeseries/src/test/scala/com/criteo/cuttle/timeseries/TimeSeriesSchedulerSpec.scala

Periods should be strict dividers of 24.

Adds support for periods of n hours

---

core/src/it/scala/com/criteo/cuttle/DatabaseITest.scala
core/src/it/scala/com/criteo/cuttle/DatabaseSuite.scala
core/src/main/scala/com/criteo/cuttle/ExecutionStreams.scala
core/src/main/scala/com/criteo/cuttle/Executor.scala
core/src/main/scala/com/criteo/cuttle/package.scala
core/src/main/scala/com/criteo/cuttle/platforms/RateLimiter.scala
core/src/test/scala/com/criteo/cuttle/ExecutorSpec.scala
cron/src/main/scala/com/criteo/cuttle/cron/CronProject.scala
timeseries/src/main/javascript/app/pages/BackfillCreate.js
timeseries/src/main/scala/com/criteo/cuttle/timeseries/CuttleProject.scala
timeseries/src/main/scala/com/criteo/cuttle/timeseries/Database.scala
timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesScheduler.scala
timeseries/src/test/scala/com/criteo/cuttle/timeseries/TimeSeriesSchedulerSpec.scala
timeseries/src/test/scala/com/criteo/cuttle/timeseries/TimeSeriesUtilsSpec.scala

as not everyone is using the git hook

Lint code with scalafmt / eslint

---

timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesApp.scala

We only cancel executions that correspond to the interval parameter of the force success command

Fix force success

---

core/src/main/scala/com/criteo/cuttle/Executor.scala

This is not used to force sucess anymore

Remove dead code

---

build.sbt
core/src/main/scala/com/criteo/cuttle/Database.scala
core/src/main/scala/com/criteo/cuttle/Executor.scala

Those classes will be used outside of cuttle

Make Executor and DatabaseConfig visibility public

---

core/src/main/scala/com/criteo/cuttle/Executor.scala
timeseries/src/main/scala/com/criteo/cuttle/timeseries/Internal.scala
timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesApp.scala

it cleans up the code from unneccessary noise

move internal objects to Internal or TimeSeriesApp objects

---

build.sbt
core/src/test/scala/com/criteo/cuttle/ExecutorSpec.scala

Update mysql-connector-java to 8.0.17

---

.scala-steward.conf

Until we bump cats on lolhttp side

[scala-steward] Ignore cats and its dependents libs

---

README.md
core/src/main/scala/com/criteo/cuttle/platforms/local/LocalPlatform.scala

LocalPlatform errors

---

build.sbt

Also update:
- transitive dependencies: cats-core, circe, doobie
- scala 2.12.8

Update lolhttp to 0.13.0

---

.travis.yml
package.json
timeseries/src/main/javascript/app/pages/Workflow.js
yarn.lock

it has been deprecated for several years now

Remove unused vega graphs

---

.scala-steward.conf
build.sbt

As we get errors such as: `Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.zaxxer.nuprocess.internal.LibJava8`

Nuprocess downgrade

---

core/src/main/scala/com/criteo/cuttle/Utils.scala
cron/src/main/scala/com/criteo/cuttle/cron/CronApp.scala
cron/src/main/scala/com/criteo/cuttle/cron/CronModel.scala
cron/src/main/scala/com/criteo/cuttle/cron/CronScheduler.scala
cron/src/main/scala/com/criteo/cuttle/cron/UI.scala

[Cuttle-Cron] Implement 'Run Now' feature.

---

README.md
build.sbt
core/src/main/scala/com/criteo/cuttle/Executor.scala

We use this method outside of cuttle

Make relaunch public

---

core/src/main/scala/com/criteo/cuttle/Executor.scala

Code has been factorized with relaunch which is specific to jobs

Add a relaunch method to relaunch specific executions

---

core/src/main/scala/com/criteo/cuttle/Executor.scala
timeseries/src/main/scala/com/criteo/cuttle/timeseries/Database.scala
timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesScheduler.scala

Default values are:
30 days for executions
1 day for state
10 max versions

Add default values to clean state DB

---

core/src/main/scala/com/criteo/cuttle/Executor.scala

The former version made each version hold a copy
of all the runningState, even though the index
will be queried on less elements (in an extreme case
a single element).
Reduce the size of the index by keeping only elements
that will be queried.

[executor] Reduce the size of the index

---

core/src/main/scala/com/criteo/cuttle/Executor.scala
cron/src/main/scala/com/criteo/cuttle/cron/CronApp.scala
cron/src/main/scala/com/criteo/cuttle/cron/CronExpression.scala
cron/src/main/scala/com/criteo/cuttle/cron/CronModel.scala
cron/src/main/scala/com/criteo/cuttle/cron/CronPipeline.scala
cron/src/main/scala/com/criteo/cuttle/cron/CronScheduler.scala
cron/src/main/scala/com/criteo/cuttle/cron/UI.scala
cron/src/main/scala/com/criteo/cuttle/cron/package.scala
examples/src/main/scala/com/criteo/cuttle/examples/HelloCronDagScheduling.scala
examples/src/main/scala/com/criteo/cuttle/examples/HelloCronScheduling.scala
timeseries/src/main/scala/com/criteo/cuttle/timeseries/Database.scala

2 main fixes:
* Any job failure would break the whole execution loop for all jobs
* Jobs would ignore configured retries by starting at their max attempt
Additionally, the UI was improved a bit and the code reformatted properly

Cron fixes

---

README.md
build.sbt

* Fix time series executions view not updating (#562)
* Cron context fixes (#560)

Bump to 0.11.6

---

build.sbt
core/src/main/scala/com/criteo/cuttle/Database.scala

This reverts commit f7c4c4fd609733280f1e3590960aa771da2020fa.

Revert "Use mariadb driver instead of mysql (#537)"

---

build.sbt
core/src/main/scala/com/criteo/cuttle/Database.scala

Allows to override jdbc connectionString

---

build.sbt

this will expose new api method `rawArchivedExecutions` in `Executor.scala`

bump version
