criteo/cuttle

core/src/main/scala/com/criteo/cuttle/Cuttle.scala, core/src/main/scala/com/criteo/cuttle/Execution.scala, core/src/main/scala/com/criteo/cuttle/LocalPlatform.scala, timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeseriesApp.scala, timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeseriesScheduler.scala
Now, when submitting a (job,context) while the same (job,context) is already running, no new execution will be submitted, and a pointer to the existing one will be returned. It means that you can't execute the same (job,context) concurrently several times.
=> Change the Executor semantic.

build.sbt, core/src/main/scala/com/criteo/cuttle/Graph.scala, core/src/test/scala/com/criteo/cuttle/CuttleSpec.scala, examples/src/main/scala/com/criteo/cuttle/examples/HelloWorld.scala, examples/src/test/scala/com/criteo/cuttle/examples/TestExample.scala, localdb/src/main/scala/com/criteo/cuttle/localdb/LocalDB.scala, timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeseriesScheduler.scala, timeseries/src/test/scala/com/criteo/cuttle/timeseries/TimeSeriesSpec.scala
Make the HelloWorld example simple again. Introduce a failure case
to demonstrate failing jobs. Fix the `example' command to automatically
start a local database.
=> Simplify the Scala API, and fix the HelloWorld example.

core/src/main/scala/com/criteo/cuttle/App.scala, core/src/main/scala/com/criteo/cuttle/Cuttle.scala, core/src/main/scala/com/criteo/cuttle/Execution.scala, core/src/main/scala/com/criteo/cuttle/JsonApi.scala, examples/src/main/scala/com/criteo/cuttle/examples/HelloWorld.scala
We define a retry as an execution (job, context) that fail and is followed
by a new attempt to execute it. When it happens, instead of just executing
again right away, we throttle it based on a RetryStrategy function. The default
strategy implements an exponential backoff retry delay.
It also allow us to define a list of failing executions that will appear in the
UI, and we define a new API endpoint for it.
=> Throttle execution retries.

core/src/main/scala/com/criteo/cuttle/App.scala, core/src/main/scala/com/criteo/cuttle/Database.scala, core/src/main/scala/com/criteo/cuttle/Executor.scala, core/src/main/scala/com/criteo/cuttle/Scheduling.scala, core/src/test/scala/com/criteo/cuttle/CuttleSpec.scala, timeseries/src/main/scala/com/criteo/cuttle/timeseries/Database.scala, timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeseriesScheduler.scala
The `executions` table now contains a `context_id` column instead of a
JSON representation of contexts. The scheduler provides an SQL query to
translate these ids into JSON. It is also possible to provide a custom
SQL query to get execution logs for only a subset of all contexts.
=> Move MySQL storage and querying logic for contexts to the scheduler

core/src/main/javascript/actions.js
The correct syntax is:
`([project, workflow]: [Project, Workflow]) =>`
Which fails at type checking, because flow cannot guess JSONs structure
So let’s just remove this, side note, for objects the notation is:
`({ foo, bar = 2 }: { foo: number, bar?: number }) =>`
=> [actions] remove array destructuring with flow type checking

core/src/main/scala/com/criteo/cuttle/Database.scala, core/src/main/scala/com/criteo/cuttle/Executor.scala
Change MySQL column type (allows up to 16MB), and handle the error
properly. If we can't store the stream, just continue anyway.
=> Streams storage.

core/src/main/scala/com/criteo/cuttle/Executor.scala, timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesScheduler.scala, timeseries/src/test/scala/com/criteo/cuttle/timeseries/TimeSeriesSpec.scala
2 executions cannot have the same ordering, even if it is the same job and the same context ordering.
=> Fix ordering

core/src/main/scala/com/criteo/cuttle/Executor.scala, timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesScheduler.scala
- no intersecting backfills
- no backfills before a job's startDate
- no backfilling partial periods
bonus: the scheduler won't run jobs whose dependants are running (this
is possible because of backfills)
=> TimeSeries: add checks before creating a new backfill

core/src/main/javascript/app/pages/BackfillCreate.js, timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesApp.scala, timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesScheduler.scala
Currently backfill creation failures are ignored client side.
This commit fixes this by preventing submit and displaying server error to user.
=> [backfills] Creation error client display

timeseries/src/main/scala/com/criteo/cuttle/timeseries/Database.scala, timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesApp.scala, timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesScheduler.scala, timeseries/src/main/scala/com/criteo/cuttle/timeseries/intervals/IntervalMap.scala, timeseries/src/test/scala/com/criteo/cuttle/timeseries/intervals/IntervalMapSpec.scala
- fix a bug in `IntervalMap.whenIsUndef` where it would fail if the
argument had two adjacent intervals
- fix a bug in route `/api/timeseries/calendar` where it would fail if
one hour was before the startDate of every job
- stop serializing Running jobs (would cause these jobs to be stuck upon
reboot)
- correctly handle changes of a job's startDate
- correctly handle removal of a job from the graph
=> TimeSeries: a few fixes

core/src/main/javascript/app/pages/CalendarFocus.js, timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesApp.scala, timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesScheduler.scala
to avoid heavy transfers when visualizing execution for large periods
=> Aggregate execution data server-side

core/src/main/javascript/app/pages/BackfillCreate.js, package.json, yarn.lock
- css improvements
- environment name confirmation
- date mask
=> Backfills screen improvements

core/src/main/javascript/app/pages/Backfill.js, core/src/main/javascript/app/pages/BackfillCreate.js, examples/src/main/scala/com/criteo/cuttle/examples/HelloWorld.scala, timeseries/src/main/scala/com/criteo/cuttle/timeseries/Internal.scala, timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesApp.scala
=> Fixes backfill creation

core/src/main/javascript/app/pages/ExecutionLogs.js
Data was declared as a new component  on every render.
=> Avoid to remount table on each render

core/src/main/scala/com/criteo/cuttle/Database.scala
Otherwise if you try to obtain the transactor several times, it will create several connection pool. Moreover because of the locking mechanism it will deadlock.
=> Database.connect shoud reuse transactor for a given DatabaseConfig

core/src/main/scala/com/criteo/cuttle/Executor.scala, core/src/main/scala/com/criteo/cuttle/platforms/WaitingExecutionQueue.scala, core/src/main/scala/com/criteo/cuttle/platforms/local/LocalPlatform.scala
To avoid memory leak for long execution registering several cancel listeners,
we now allow to unsubscribe when the code is not anymore interested by the cancel
signal.
=> Better cancel listener design

core/src/main/scala/com/criteo/cuttle/App.scala, core/src/main/scala/com/criteo/cuttle/Cuttle.scala, core/src/main/scala/com/criteo/cuttle/Executor.scala, core/src/main/scala/com/criteo/cuttle/Logger.scala, core/src/main/scala/com/criteo/cuttle/Metrics.scala, core/src/main/scala/com/criteo/cuttle/Scheduling.scala, core/src/main/scala/com/criteo/cuttle/Utils.scala, core/src/main/scala/com/criteo/cuttle/package.scala, timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesScheduler.scala, timeseries/src/main/scala/com/criteo/cuttle/timeseries/intervals/IntervalMap.scala
Add the endpoint /api/metrics for Prometheus.
Delete a logging package.
Small refactoring in Executor.scala.
=> Add the endpoint /api/metrics for Prometheus.

core/src/main/scala/com/criteo/cuttle/App.scala, core/src/main/scala/com/criteo/cuttle/Executor.scala, core/src/main/scala/com/criteo/cuttle/Metrics.scala, timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesScheduler.scala
Now we can add help and type prometheus like comments to our metrics.
Each Prometheus metric is defined by its name and set of labels so our metric model reflect this directly by implementing a Map: set of labels to value. 
For instance we support only a gauge type of metrics.
=> Update Metrics model.

core/src/main/javascript/app/pages/ExecutionLogs.js, core/src/main/scala/com/criteo/cuttle/App.scala, core/src/main/scala/com/criteo/cuttle/Executor.scala, core/src/main/scala/com/criteo/cuttle/Workflow.scala, timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesApp.scala
- new route /api/executions/relaunch?jobs=
- new method in Executor `def relaunch` that  is invoked by new route
- code rearrangement in Executor
=> allow to relaunch all stuck jobs

core/src/main/scala/com/criteo/cuttle/platforms/local/LocalPlatform.scala, core/src/main/scala/com/criteo/cuttle/platforms/local/package.scala
`private[cuttle] object LocalPlatform` restricts usage of LocalPlatform's apply function outside of cuttle package
=> remove companion object that was shadowing an apply function

core/src/main/scala/com/criteo/cuttle/Database.scala, devloop.js, examples/src/test/scala/com/criteo/cuttle/examples/TestExample.scala
We allow to configure multiple MySQL endpoints for failover when one of them is unavailable.
When starting a new connection, the driver always tries to connect to the primary host first and, if required, fails over to the secondary hosts on the list sequentially when communication problems are experienced.
https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-config-failover.html
=> allow multiple MySQL endpoints

core/src/main/scala/com/criteo/cuttle/App.scala, core/src/main/scala/com/criteo/cuttle/CuttleProject.scala, core/src/main/scala/com/criteo/cuttle/ExecutionContexts.scala, core/src/main/scala/com/criteo/cuttle/Executor.scala, core/src/main/scala/com/criteo/cuttle/Utils.scala, core/src/main/scala/com/criteo/cuttle/package.scala, core/src/main/scala/com/criteo/cuttle/platforms/http/HttpPlatform.scala, timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesApp.scala, timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesScheduler.scala
The split is as follows:
- 1 thread pool for Cuttle's HTTP server with low thread limit
- 1 thread pool to run side effects
- 1 thread pool for internal use by side effects (which returns Futures from an execution context)
Other: fixed some typos
=> Use dedicated ExecutionContexts

core/src/main/scala/com/criteo/cuttle/Authentication.scala, core/src/main/scala/com/criteo/cuttle/ExecutionStreams.scala
Executions logs are stored in MySQL table in a column of type MEDIUMTEXT taht allows up to 16,777,215 bytes = 16 MiB values.
We truncated our log to 64kb before and for some applications it were too little.
Now a Cuttle User can override this value by setting a JVM property  com.criteo.cuttle.maxExecutionLogSize
I also increased our heuristically calculated default value for this setting as 512Kb or 524,288 bytes.
=> allow to parametrize executions log size

core/src/main/scala/com/criteo/cuttle/App.scala, core/src/main/scala/com/criteo/cuttle/Executor.scala, core/src/main/scala/com/criteo/cuttle/Metrics.scala, examples/src/main/scala/com/criteo/cuttle/examples/HelloWorld.scala, timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesApp.scala, timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesScheduler.scala
Add tags to metrics that allows any prometheus aggregates instead of code avg aggregate.
Example: `max(cuttle_timeseries_scheduler_absolute_latency_epoch_seconds{tags=~"^(.*,)?hello(,.*)?$"})`
=> Tag metrics

timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesScheduler.scala, timeseries/src/main/scala/com/criteo/cuttle/timeseries/package.scala
This allows to depend on multiple periods through one dependency. The
meaning of the offset has also been reversed. An offset is now applied
to the desired period to get the period the dependency has to satisfy.
=> Separate low and high bounds in TimeSeriesDependency

core/src/main/scala/com/criteo/cuttle/CuttleProject.scala
This change allow a more flexible way to start Cuttle. You can now get only needed routes and bootstrap the server externally (to add some routes or custom behaviour)
=> Create server outside of cuttle

core/src/main/javascript/App.js, core/src/main/javascript/ApplicationState.js, core/src/main/javascript/app/menu/Menu.js, core/src/main/javascript/app/pages/Jobs.js, core/src/main/javascript/index.js
list of jobs that can be sliced by status parameter:
- all - all jobs
- active - all jobs that produce executions
- paused - stopped jobs that don't produce executions at the moment
=> introducing list of jobs

core/src/main/scala/com/criteo/cuttle/Workflow.scala, core/src/main/scala/com/criteo/cuttle/graph/mutable/Graph.scala, core/src/main/scala/com/criteo/cuttle/graph/package.scala, timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesScheduler.scala, timeseries/src/test/scala/com/criteo/cuttle/timeseries/TimeSeriesSpec.scala
V being the number of jobs and E the number of dependencies
Supersedes https://github.com/criteo/cuttle/pull/236 taking into @loicknuchel comments and drops the cycle identification for this change.
See `TimeSeriesUtils.validate()`
=> Refactor graph validation to reduce complexity from O(VE) to O(V+E)

core/src/main/scala/com/criteo/cuttle/platforms/WaitingExecutionQueue.scala
When several actions were queued concurrently in the same
WaitingExecutionQueue, only the last one remained.
=> Fixes race condition in waiting execution queue

core/src/main/scala/com/criteo/cuttle/App.scala, timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesApp.scala
Fixes a calendar display bug that occurred in some timezones
=> Send dates instead of instants in /api/timeseries/calendar

core/src/main/scala/com/criteo/cuttle/Executor.scala, timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesApp.scala, timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesScheduler.scala, timeseries/src/test/scala/com/criteo/cuttle/timeseries/TimeSeriesSpec.scala
Automatically resolve valid backfills on subperiods instead of requesting the backfill to be valid on the whole input period.
Assume a backfill is requested over the period t1, t2 for the jobs = {job1, job2}
For illustrative purposes, let the past execution state be as follows:
```
| time | t1 | t2 | t3 | t4 | t5 |
| job1 | OK | OK | KO | OK | OK |
| job2 | OK | OK | KO | KO | OK |
````
Then the backfill will be lauched on {t1, t2} for jobs {job1, job2}, on {t4} for {job1} and on {t5} for {job1, job2}
=> Resolve backfills on valid subperiods

core/src/main/javascript/app/components/StreamView.js
This PR changes two things on the StreamView. component of the frontend app, to allow to copy-paste several lines of log properly;
- Puts the timestamps as user-select: none to disable the possibity to highlight it
- Changes the paragraph tag to a more general div one, to stop inserting newlines when selecting log lines and pasting them
I tested it on Firefox 61, Chrome 67 and Safari 11.1.1, on macOS 10.13.5.
=> Allow to properly copy-paste logs from StreamView

timeseries/src/main/javascript/app/pages/Jobs.js, timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesApp.scala
Why this change?
The TimeSeriesScheduler.state method returns a snapshot of the current execution states and is used in several of the API endpoints, such as the calendar view. For methods polling such API endpoints (through the method `sse`), the execution states were not updated between each API call, resulting in an absence in changes in the UI.
=> [Timeseries UI] Fixed empty jobs view and non-updated states in calendar view

build.sbt, core/src/main/scala/com/criteo/cuttle/ExecutionStreams.scala, core/src/main/scala/com/criteo/cuttle/Executor.scala
- Fix a complexity issue is the execution submission loop
- Fix an issue with IO & STM in ExecutionStreams
=> Performance issue with large number of execution

timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesApp.scala
The current implementation used to do a linear scan of all the failing executions to check whether an execution failed or not, for each job and each execution period.
=> Optimize failure state retrieval in calendar view

build.sbt, core/src/main/scala/com/criteo/cuttle/Executor.scala, core/src/test/scala/com/criteo/cuttle/ExecutorSpec.scala, timeseries/src/main/javascript/app/menu/Menu.js, timeseries/src/main/scala/com/criteo/cuttle/timeseries/CuttleProject.scala, timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesApp.scala, timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesScheduler.scala, timeseries/src/test/scala/com/criteo/cuttle/timeseries/TimeSeriesSchedulerSpec.scala
No Execution instance is created when a job is paused.
On the UI side, the paused execution navigation menu was removed.
=> Move pause execution management inside scheduler

core/src/main/scala/com/criteo/cuttle/Database.scala, core/src/main/scala/com/criteo/cuttle/ThreadPools.scala, core/src/main/scala/com/criteo/cuttle/Utils.scala
Others: make the scheduler checking locks on the cuttle state DB create daemon threads
=> Centralize and expose thread pool instantiation

timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesScheduler.scala, timeseries/src/test/scala/com/criteo/cuttle/timeseries/TimeSeriesSpec.scala
Due to https://github.com/criteo/cuttle/pull/299, JobState.Done
parsing was not backwards compatible (field projectVersion introduced
in case class). The choice has been made here to assign a default
version instead of making it optional, in order to minimize bugfix
impact on the rest of the codebase.
=> Makes JobState parsing more lenient

build.sbt, timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesApp.scala
Since the version number has been added to the job states, we get
multiple intervals for each job and we can't use the fisrt we get anymore.
We merge all the intervals to retrieve their union and discard the version
in this case.
=> Fix the lastruns timeseries endpoint

timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesScheduler.scala, timeseries/src/test/scala/com/criteo/cuttle/timeseries/TimeSeriesSchedulerIntegrationTests.scala, timeseries/src/test/scala/com/criteo/cuttle/timeseries/TimeSeriesSchedulerSpec.scala
The bug was caused by the incorrect resolution of completed parent dependencies
which spanned over contiguous time intervals, which were treated as disjoint
intervals intead of a single interval.
=> [Bugfix] Jobs todo never launched

timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesScheduler.scala
Was breaking basic features such as pattern matching on `TimeSeriesContext` values.
=> `TimeSeriesContext` companion object is public again

build.sbt, core/src/it/scala/com/criteo/cuttle/DatabaseITest.scala, core/src/it/scala/com/criteo/cuttle/DatabaseSuite.scala, core/src/main/scala/com/criteo/cuttle/Database.scala, core/src/main/scala/com/criteo/cuttle/DoobieLogsHandler.scala, core/src/main/scala/com/criteo/cuttle/ExecutionStreams.scala, core/src/main/scala/com/criteo/cuttle/Executor.scala, core/src/main/scala/com/criteo/cuttle/ThreadPools.scala, core/src/main/scala/com/criteo/cuttle/Utils.scala, core/src/main/scala/com/criteo/cuttle/platforms/RateLimiter.scala, core/src/test/scala/com/criteo/cuttle/ExecutorSpec.scala, timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesApp.scala, timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesScheduler.scala, timeseries/src/main/scala/com/criteo/cuttle/timeseries/intervals/IntervalMap.scala
New version: 0.5.0
bumping FP libs:
catsCore = "1.5.0"
circe = "0.10.1"
doobie = "0.6.0"
lolhttp = "0.12.0"
- doobie Transactor is now a cats Resource and doesn't have a shutdown method, instead we use Resource.allocated and obtain an IO to release the Hikari Pool
- doobie now needs a dedicated thread pool and dedicated ContextShift
- now we log each Doobie query for debug purposes
- xmap of circe is deprecated => we should use imap
- fs2.Scheduler is replaced by cats.effect.IO.timer and now needs and implicit cats.effect.Timer in the scope
- cats-mtl was removed as FunctorFilter was moved to cats-core
- couple of logs were added
=> bumping lolhttp, cats, doobie. Removing cats-mtl

core/src/main/scala/com/criteo/cuttle/Database.scala, core/src/main/scala/com/criteo/cuttle/Executor.scala, core/src/main/scala/com/criteo/cuttle/ThreadPools.scala, core/src/main/scala/com/criteo/cuttle/Utils.scala, cron/src/main/scala/com/criteo/cuttle/cron/CronApp.scala, cron/src/main/scala/com/criteo/cuttle/cron/CronModel.scala, cron/src/main/scala/com/criteo/cuttle/cron/CronProject.scala, cron/src/main/scala/com/criteo/cuttle/cron/CronScheduler.scala, cron/src/main/scala/com/criteo/cuttle/cron/Database.scala, cron/src/main/scala/com/criteo/cuttle/cron/package.scala, examples/src/main/scala/com/criteo/cuttle/examples/HelloCronScheduling.scala, timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesApp.scala
MVP of Cron Scheduler API.
Main features:
- CronApp class with minimalistic public and private API was created,
supported API is listed under https://documenter.getpostman.com/view/3548308/RznCs12X
Briefly we can see a status of a job, list job executions, see execution's logs and
pause/resume a job.
- CronProject takes care of instantiation of db connection, executor, scheduler
and CronApp API server
- HelloCronScheduling example was updated accordingly, check it out!
Others:
- introducing thread pool for Cron
- sse method moved to global cuttle utils package object
- state of CronScheduler became a separate class with methods which allow atomic mutation of 
underlying stm
- some scalafmt was applied to TimeSeriesApp
=> Cron scheduler api

build.sbt, cron/src/main/scala/com/criteo/cuttle/cron/CronModel.scala, cron/src/main/scala/com/criteo/cuttle/cron/CronScheduler.scala
- Cron scheduling loop stopped when a job reached the maximum number of retries,
now it fixed by completing the scheduling window
- CronContext has been made public as it needs to be used by clients
=> fix cron loop halt when reaching the maximum number of retries

cron/src/main/scala/com/criteo/cuttle/cron/CronProject.scala
it prevents from crashing when environment variables(like DATABASE_USERNAME) are not set
=> make defaults lazy for cron

core/src/main/scala/com/criteo/cuttle/Database.scala, core/src/main/scala/com/criteo/cuttle/ExecutionStreams.scala, core/src/main/scala/com/criteo/cuttle/Executor.scala, cron/src/main/scala/com/criteo/cuttle/cron/CronProject.scala, examples/src/main/scala/com/criteo/cuttle/examples/HelloTimeSeries.scala, timeseries/src/main/scala/com/criteo/cuttle/timeseries/CuttleProject.scala, timeseries/src/main/scala/com/criteo/cuttle/timeseries/Database.scala, timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesApp.scala, timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesScheduler.scala, timeseries/src/test/scala/com/criteo/cuttle/timeseries/TimeSeriesSchedulerIntegrationTests.scala
Refactoring how the TimeSeriesScheduler is instantiated (it was
a typeclass on Scheduling before but now we don't need to retrieve
the instance implicitely).
Also cleaning the code duplication between CuttleProject.start &
CuttleProject.build
=> Configurable logs & timeseries state retention

timeseries/src/main/javascript/App.js, timeseries/src/main/javascript/ApplicationState.js, timeseries/src/main/javascript/app/pages/ExecutionLogs.js, timeseries/src/main/javascript/app/pages/Jobs.js, timeseries/src/main/javascript/index.js, timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesApp.scala
During the creation of the Jobs screen, the previous Paused executions Screen has been removed from UI. It included the Resume All/Filtered jobs feature.
This PR does:
- Remove Paused executions dead code
- Moves Pause/Resume All/Filtered jobs action to the Jobs Screen
=> Pause/Resume Jobs

cron/src/main/scala/com/criteo/cuttle/cron/package.scala
we were comparing wrong objects in the function that defines a list of executions per job
=> make running executions appear in the ui

build.sbt, core/src/main/scala/com/criteo/cuttle/Executor.scala, core/src/test/scala/com/criteo/cuttle/ExecutorSpec.scala, examples/src/main/scala/com/criteo/cuttle/examples/HelloTimeSeries.scala
previous failures are available on execution object in order to enable users to stop their jobs based on the run history
=> add previous failures to execution object

timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesScheduler.scala, timeseries/src/test/scala/com/criteo/cuttle/timeseries/TimeSeriesSchedulerSpec.scala
This was caused because we create one backfill for each interval. Now that
we track a different interval for each version it means that asking for a
backfill we often create several backfill for the same jobs for contiguous
intervals.
This fix merge them together when possible.
=> Fix fragmented backfill creation

timeseries/src/main/javascript/app/menu/MenuHeader.js
It uses overflow ellipsis to hide long name, and we add a `title` to the span so you can get the whole name by hovering it.
=> Fix long project name in header

build.sbt, core/src/main/scala/com/criteo/cuttle/Executor.scala, cron/src/main/scala/com/criteo/cuttle/cron/package.scala, timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesApp.scala
I don't know why some function had the XA passed as argument
since Executor instance itself maintain handle a transactor, but
it makes it more complex to call these function from the outside
so I fixed it as well.
=> Open some private API on Executor

timeseries/src/main/javascript/app/menu/MenuHeader.js, timeseries/src/main/javascript/app/pages/BackfillCreate.js, timeseries/src/main/scala/com/criteo/cuttle/timeseries/Internal.scala, timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesApp.scala
The backfilled jobs list is now sent as a real list instead of a string with comma separated ids
=> Fix a backfill issue for job ids containing a comma

core/src/it/scala/com/criteo/cuttle/TestScheduling.scala, core/src/main/scala/com/criteo/cuttle/Scheduling.scala, core/src/test/scala/com/criteo/cuttle/TestScheduling.scala, cron/src/main/scala/com/criteo/cuttle/cron/CronModel.scala, examples/src/main/scala/com/criteo/cuttle/examples/HelloCustomScheduling.scala, timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesScheduler.scala
Add a method to get an id to identify a context across
reboots of the application.
=> Add longRunningId to SchedulingContext

timeseries/src/main/javascript/app/pages/Execution.js
Messages without Timestamp / level like `--- CONTENT TRUNCATED AT xxx` are not displayed otherwise
=> [timeseries] Execution Streams > handle non standard messages in view

core/src/main/scala/com/criteo/cuttle/Executor.scala, timeseries/src/main/scala/com/criteo/cuttle/timeseries/Internal.scala
As streams can be truncated, there are debug cases where we want to get error anyway
=> Executor log execution errors

core/src/main/scala/com/criteo/cuttle/Executor.scala
As logs can be truncated over a maximum length
=> Log execution error stream as application warning

build.sbt, project/plugins.sbt
- Update mariaDB4j to 2.4.0 #399
- Update sbt-unidoc to 0.4.2 #403
- Update cron4s-core to 0.5.0 #405
- Update sbt-pgp to 1.1.2 #406
- Update nuprocess to 1.1.3 #407
- Update fingertree to 1.5.4 #408
- Update circe to 0.11.1 #409
- Update scala-stm to 0.9.1 #411
- Update scalatest to 3.0.8 #412
- Update doobie to 0.7.0 #413
- Update sbt-sonatype to 2.5 #415
=> Bulk dependencies update

timeseries/src/main/scala/com/criteo/cuttle/timeseries/Database.scala
As some previous migration feature might left one, causing rare crashes
where a backfill collide with normal state updates
=> [timeseries] DROP timeseries_state PK if it exists

README.md, build.sbt, timeseries/src/main/javascript/app/pages/Execution.js
Job execution duration display cannot go above 24h.
The moment.format function can only generate days between 1 and 31.
For durations > 24h, we display days explicitly
=> Fix job duration display

timeseries/src/main/scala/com/criteo/cuttle/timeseries/Database.scala, timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesApp.scala, timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesScheduler.scala
The executionId has been added to the Todo state
instead. The issue was that the Running state
erased the notion of backfill.
=> Remove the running state

timeseries/src/main/javascript/app/components/FancyTable.js
When the list of jobs is too big, the header of the details
of the backfill was too small to show the contents.
=> Fix UI for Backfills when screen has many jobs.

core/src/main/scala/com/criteo/cuttle/Database.scala, core/src/main/scala/com/criteo/cuttle/ExecutionStreams.scala, core/src/main/scala/com/criteo/cuttle/Executor.scala
- Switch to start_time as it is an indexed field, unlike end, which led to some issues
- Change to 1h periodicity vs each execution end
=> [core] Logs retention fix

cron/src/main/scala/com/criteo/cuttle/cron/package.scala, examples/src/main/scala/com/criteo/cuttle/examples/HelloCronDagScheduling.scala, examples/src/main/scala/com/criteo/cuttle/examples/HelloCronScheduling.scala
* Job.every method can upgrade a single Job to CronDag without a separate id
* CronExpression is still moved from Job to CronDag level, so a little code change still needed
=> Add some backward compat methods to ease the migration to CronDag

timeseries/src/main/scala/com/criteo/cuttle/timeseries/CuttleProject.scala
The new parameter was not passed down to the needing code.
=> Actually passing the new parameter down the line

build.sbt
As per https://github.com/scala/bug/issues/10572
change
-Ywarn-unused:-params
into
-Ywarn-unused:-explicits,-implicits
=> [build] Fix 'params' cannot be negated in scala 2.12

timeseries/src/main/scala/com/criteo/cuttle/timeseries/TimeSeriesApp.scala
The time series executions view (when clicking on a specific interval of a specific job in the calendar focus view) queries an url to get the list of executions, and is supposed to use server sent events to auto refresh that list.
However that url would simply serve the first snapshot and never refresh it, due to the snapshot being put in a pure IO after it has been computed.
We just fix that by putting the actual computation of the snapshot in an IO, which will refresh the server sent events properly.
=> Fix time series executions view not updating

core/src/main/scala/com/criteo/cuttle/Database.scala
This fixes an issue where the DB server becomes readonly while the application is running, and the application silently fails when trying to write to it (at least in the case of Cuttle Cron)
=> Check that the server is not readonly in DB health check

build.sbt, core/src/main/scala/com/criteo/cuttle/Database.scala
Reverts criteo/cuttle#581 for following release.
=> Revert "Revert "Use mariadb driver instead of mysql (#537)""

frontend/javascript/cron/pages/Dags.js, frontend/javascript/timeseries/pages/Jobs.js, webpack.config.js
*  Fix fonts not being loaded properly:
The path generated by webpack was missing a `/`, so it would try to load `/public/timeseriesFiraMono-[].ttf` instead of `/public/timeseries/FiraMono-[].ttf`
*  Fix Cron UI breaking when trying to sort on dates:
Absent dates would fail to parse as `new Date(<empty string>)` and break everything, so simply don't parse them
=> Frontend fixes

core/src/main/scala/com/criteo/cuttle/Executor.scala
`rawArchivedExecutions` fetches `ExecutionLog`s without expensive join.
=> [Executor] expose `rawArchivedExecutions`

core/src/main/scala/com/criteo/cuttle/Database.scala
In the read only connection, the db lock is bypassed and the transactor is
returned as is.
JIRA: DPT-2819
=> [data-catalog] create cuttle "readOnlyConnect" method
